[connections.snowflake]
account = "ETMFQTA-JCB26653"
user = "deependeryadav432@gmail.com"
password = "rjYXdeBjc4*-uwD"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "smoothies"
schema = "public"
